### ISSUE TITLE
[improvement] Remove server dependency

### ISSUE THREAD

**Issue by RyDroid** [qliavi/speedometer#1]
Hi.
Currently, the app uses PHP, so obviously it needs a server. It would be great to be able to use the app without a server.
Regards.

**Comment by aimnadze** [comment]
Thanks for the suggestion. I've been thinking about that in the past but never made a change so far.

The app uses PHP for automatic builds and revisioning. So completely removing the use of PHP will be impossible.

However based on existing `index.php` an `index.html` file can be generated. I will work on implementing this. And by the way it will allow downloading an app as a zip file.

**Comment by aimnadze** [comment]
Mozilla abandoned me and many many developers and rendered this and mant Firefox OS apps a memorial. Sorry, I cannot fix this issue.

**Comment by RyDroid** [comment]
Ok. That is sad. :-(
